/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LayoutData, LayoutHeaderAuthAction } from "./types/layout-data";
export { LayoutData, LayoutHeaderAuthAction } from "./types/layout-data";
export namespace Components {
    interface WegFooter {
        /**
          * Layout payload, supplied by the host application.  In JS / framework templates, pass the object directly (e.g. Angular `[layout]="layoutData"`, React `layout={layoutData}`, vanilla `el.layout = layoutData`).  In plain HTML, pass the same JSON as a string on the `layout` attribute.  Expected shape: ```json {   "footer": {     "social": [{ "platform": "LinkedIn", "href": "https://..." }],     "columns": [{ "links": [{ "label": "About Us", "href": "/about" }] }],     "credits": "...",     "copyright": "..."   } } ```
         */
        "layout"?: LayoutData | string;
    }
    interface WegHeader {
        /**
          * Layout payload, supplied by the host application.  Expected shape: ```json {   "header": {     "logoHref": "https://www.warwickemploymentgroup.com/",     "dropdowns": [{ "label": "Find a job", "items": [{ "label": "...", "href": "..." }] }],     "links": [{ "label": "Career advice", "href": "/career-advice" }],     "signIn": { "label": "Sign in", "href": "/account/login" },     "signOut": { "label": "Sign out", "href": "/account/login" }   } } ```
         */
        "layout"?: LayoutData | string;
        /**
          * When true, the header shows the signed-in navigation (Find a job, Dashboard, Manage Account, Sign out) instead of the CMS layout.
          * @default false
         */
        "signedIn": boolean;
        /**
          * Signed-in user's first name, shown beside the profile icon on Manage Account.
         */
        "userName"?: string;
    }
}
export interface WegHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWegHeaderElement;
}
declare global {
    interface HTMLWegFooterElement extends Components.WegFooter, HTMLStencilElement {
    }
    var HTMLWegFooterElement: {
        prototype: HTMLWegFooterElement;
        new (): HTMLWegFooterElement;
    };
    interface HTMLWegHeaderElementEventMap {
        "wegAuthClick": { action: LayoutHeaderAuthAction };
    }
    interface HTMLWegHeaderElement extends Components.WegHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWegHeaderElementEventMap>(type: K, listener: (this: HTMLWegHeaderElement, ev: WegHeaderCustomEvent<HTMLWegHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWegHeaderElementEventMap>(type: K, listener: (this: HTMLWegHeaderElement, ev: WegHeaderCustomEvent<HTMLWegHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWegHeaderElement: {
        prototype: HTMLWegHeaderElement;
        new (): HTMLWegHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "weg-footer": HTMLWegFooterElement;
        "weg-header": HTMLWegHeaderElement;
    }
}
declare namespace LocalJSX {
    interface WegFooter {
        /**
          * Layout payload, supplied by the host application.  In JS / framework templates, pass the object directly (e.g. Angular `[layout]="layoutData"`, React `layout={layoutData}`, vanilla `el.layout = layoutData`).  In plain HTML, pass the same JSON as a string on the `layout` attribute.  Expected shape: ```json {   "footer": {     "social": [{ "platform": "LinkedIn", "href": "https://..." }],     "columns": [{ "links": [{ "label": "About Us", "href": "/about" }] }],     "credits": "...",     "copyright": "..."   } } ```
         */
        "layout"?: LayoutData | string;
    }
    interface WegHeader {
        /**
          * Layout payload, supplied by the host application.  Expected shape: ```json {   "header": {     "logoHref": "https://www.warwickemploymentgroup.com/",     "dropdowns": [{ "label": "Find a job", "items": [{ "label": "...", "href": "..." }] }],     "links": [{ "label": "Career advice", "href": "/career-advice" }],     "signIn": { "label": "Sign in", "href": "/account/login" },     "signOut": { "label": "Sign out", "href": "/account/login" }   } } ```
         */
        "layout"?: LayoutData | string;
        /**
          * Fired when the user clicks Sign in or Sign out. Call `event.preventDefault()` in the host to handle navigation/logout yourself.
         */
        "onWegAuthClick"?: (event: WegHeaderCustomEvent<{ action: LayoutHeaderAuthAction }>) => void;
        /**
          * When true, the header shows the signed-in navigation (Find a job, Dashboard, Manage Account, Sign out) instead of the CMS layout.
          * @default false
         */
        "signedIn"?: boolean;
        /**
          * Signed-in user's first name, shown beside the profile icon on Manage Account.
         */
        "userName"?: string;
    }

    interface WegFooterAttributes {
        "layout": LayoutData | string;
    }
    interface WegHeaderAttributes {
        "layout": LayoutData | string;
        "signedIn": boolean;
        "userName": string;
    }

    interface IntrinsicElements {
        "weg-footer": Omit<WegFooter, keyof WegFooterAttributes> & { [K in keyof WegFooter & keyof WegFooterAttributes]?: WegFooter[K] } & { [K in keyof WegFooter & keyof WegFooterAttributes as `attr:${K}`]?: WegFooterAttributes[K] } & { [K in keyof WegFooter & keyof WegFooterAttributes as `prop:${K}`]?: WegFooter[K] };
        "weg-header": Omit<WegHeader, keyof WegHeaderAttributes> & { [K in keyof WegHeader & keyof WegHeaderAttributes]?: WegHeader[K] } & { [K in keyof WegHeader & keyof WegHeaderAttributes as `attr:${K}`]?: WegHeaderAttributes[K] } & { [K in keyof WegHeader & keyof WegHeaderAttributes as `prop:${K}`]?: WegHeader[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "weg-footer": LocalJSX.IntrinsicElements["weg-footer"] & JSXBase.HTMLAttributes<HTMLWegFooterElement>;
            "weg-header": LocalJSX.IntrinsicElements["weg-header"] & JSXBase.HTMLAttributes<HTMLWegHeaderElement>;
        }
    }
}
